### ISSUE TITLE
System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.

### ISSUE THREAD

**Issue by Confusioner** [dancodru/ZeoScope#1]
I got a Exception in the middle of runtime. Computer was idle and this issue show up.
# 

Date: 23.06.2012 22:30:49
System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at SlimDX.Direct3D9.Font.DrawString(Sprite sprite, String text, Rectangle rectangle, DrawTextFormat format, Int32 color)
   at SlimDX.Direct3D9.Font.DrawString(Sprite sprite, String text, Int32 x, Int32 y, Color4 color)
   at ZeoScope.ScopePanel.DrawText() in D:\Git\ZeoScope\src\ZeoScopeApp\ScopePanel.cs:line 629
   at ZeoScope.ScopePanel.RenderDevice() in D:\Git\ZeoScope\src\ZeoScopeApp\ScopePanel.cs:line 441
   at ZeoScope.MainScreen.Render() in D:\Git\ZeoScope\src\ZeoScopeApp\MainScreen.cs:line 97
   at ZeoScope.MainScreen.<>c__DisplayClass3.<Main>b__1() in D:\Git\ZeoScope\src\ZeoScopeApp\MainScreen.cs:line 573
   at SlimDX.Windows.MessagePump.IdleHandler.OnIdle(Object sender, EventArgs e)
   at System.Windows.Forms.Application.ThreadContext.System.Windows.Forms.UnsafeNativeMethods.IMsoComponent.FDoIdle(Int32 grfidlef)
   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(Int32 dwComponentID, Int32 reason, Int32 pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.Run(Form mainForm)
   at SlimDX.Windows.MessagePump.Run(Form form, MainLoop mainLoop)
   at ZeoScope.MainScreen.Main(String[] args) in D:\Git\ZeoScope\src\ZeoScopeApp\MainScreen.cs:line 569

**Comment by Confusioner** [comment]
Its turns out a malfunctioning motherboard.

**Comment by dancodru** [comment]
Are you still seeing the problem?

On Sun, Jun 24, 2012 at 4:27 AM, Confusioner <
reply@reply.github.com
