### ISSUE TITLE
Problem launching ZeoScope on Windows 7

### ISSUE THREAD

**Issue by technohedron** [dancodru/ZeoScope#2]
Hi, 
## I am not able to run ZeoScope on my Asus Eee notebook with windows 7 with upgraded directx: right after clicking on the program file a window shows up:

SlimDX.Direct3D9.Direct3D9Exception: D3DERR_INVALIDCALL: Invalid call (-2005530516)
   at SlimDX.Result.Throw[T](Object dataKey, Object dataValue)
   at SlimDX.Result.Record[T](Int32 hr, Boolean failed, Object dataKey, Object dataValue)
   at SlimDX.Direct3D9.Device..ctor(Direct3D direct3D, Int32 adapter, DeviceType deviceType, IntPtr controlHandle, CreateFlags createFlags, PresentParameters[] presentParameters)
   at ZeoScope.ScopePanel.CreateDevice() in D:\Git\ZeoScope\src\ZeoScopeApp\ScopePanel.cs:line 388
   at ZeoScope.ScopePanel..ctor() in D:\Git\ZeoScope\src\ZeoScopeApp\ScopePanel.cs:line 98
   at ZeoScope.MainScreen.InitializeComponent() in D:\Git\ZeoScope\src\ZeoScopeApp\MainScreen.designer.cs:line 72
##    at ZeoScope.MainScreen.Main(String[] args) in D:\Git\ZeoScope\src\ZeoScopeApp\MainScreen.cs:line 549

my Asus Eee is not able to do more than 1024x768, could be this the issue ? Last 4 hours I tried everything imaginable to make it run. The program is running fine on my second laptop with windows xp and the same directx.

**Comment by dancodru** [comment]
Try the instructions on this page and send the debug output http://stackoverflow.com/questions/2497641/slimdx-device-reset-crashes-with-a-d3derr-invalidcall-invalid-call-200553051
