### ISSUE TITLE
Windows 8 Install doesn't work

### ISSUE THREAD

**Issue by robtheviking** [dancodru/ZeoScope#3]
# 
# 

Date: 2013-10-19 4:33:03 PM
SlimDX.Direct3D9.Direct3DX9NotFoundException: Direct3DX 9 was not found. Please install the latest DirectX end-user redistributable package from Microsoft. ---> System.Runtime.InteropServices.SEHException: External component has thrown an exception.
   at D3DXCheckVersion(UInt32 , UInt32 )
   at SlimDX.Direct3D9.Direct3D..ctor()
   --- End of inner exception stack trace ---
   at SlimDX.Direct3D9.Direct3D..ctor()
   at ZeoScope.ScopePanel.CreateDevice() in D:\Git\ZeoScope\src\ZeoScopeApp\ScopePanel.cs:line 388
   at ZeoScope.ScopePanel..ctor() in D:\Git\ZeoScope\src\ZeoScopeApp\ScopePanel.cs:line 98
   at ZeoScope.MainScreen.InitializeComponent() in D:\Git\ZeoScope\src\ZeoScopeApp\MainScreen.designer.cs:line 72
   at ZeoScope.MainScreen.Main(String[] args) in D:\Git\ZeoScope\src\ZeoScopeApp\MainScreen.cs:line 549

**Comment by dancodru** [comment]
Did you install directX form here
http://www.microsoft.com/en-us/download/details.aspx?id=35 ?

**Comment by dancodru** [comment]
this has changed my life http://huff.to/yalU1b

**Comment by dancodru** [comment]
FW:Important Info I was able to reduce my monthly payments by $300
with the national program! http://goo.gl/lh04gy

**Comment by dancodru** [comment]
FW:Dancodru/zeoscope this has helped me so much http://hrld.us/ySRW5M
